### ISSUE TITLE
Timestamp should be int64

### ISSUE THREAD

**Issue by andygrunwald** [a-sk/go-nagios-log-analyzer#3]
I discovered that the `Timestamp`of the datastructure `ParsedLine` is `int`.
According to the golang docs, a Unix timestamp should be int64 to be safe.
See https://golang.org/pkg/time/#Unix

**Comment by a-sk** [comment]
Yeah, you are right.
If you are interested, pull requests are welcome.

**Comment by andygrunwald** [comment]
I opened https://github.com/a-sk/go-nagios-log-analyzer/pull/4
